import { BiLogoPostgresql } from "react-icons/bi";
import {
  SiAmazons3,
  SiBootstrap,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiFramer,
  SiGithub,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiLaravel,
  SiNextdotjs,
  SiNodedotjs,
  SiPrisma,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiReacttable,
  SiRedis,
  SiRedux,
  SiSass,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiVuedotjs,
} from "react-icons/si";

type stacksProps = {
  [key: string]: JSX.Element;
};

const ICON_SIZE: number = 24;

export const STACKS: stacksProps = {
  "Express.js": <SiExpress size={ICON_SIZE} />,
  "Framer Motion": <SiFramer size={ICON_SIZE} />,
  "Next.js": <SiNextdotjs size={ICON_SIZE} />,
  "Node JS": <SiNodedotjs size={ICON_SIZE} color="#418A3F" />,
  "React Hook Form": <SiReacthookform size={ICON_SIZE} color="#ED5991" />,
  "React Query": <SiReactquery size={ICON_SIZE} color="#FF4055" />,
  "React Router": <SiReactrouter size={ICON_SIZE} color="#F54350" />,
  "React Table": <SiReacttable size={ICON_SIZE} color="#1C8FC8" />,
  "React.js": <SiReact size={ICON_SIZE} color="#149FCB" />,
  "Vue. js": <SiVuedotjs size={ICON_SIZE} color="#42B883" />,
  AWS: <SiAmazons3 size={ICON_SIZE} color="#E05141" />,
  Bootstrap: <SiBootstrap size={ICON_SIZE} color="#7952B3" />,
  CSS: <SiCss3 size={ICON_SIZE} color="#214CE5" />,
  Docker: <SiDocker size={ICON_SIZE} color="#0DB7ED" />,
  Firebase: <SiFirebase size={ICON_SIZE} color="#FFCA2F" />,
  Github: <SiGithub size={ICON_SIZE} />,
  GraphQL: <SiGraphql size={ICON_SIZE} color="#F6009C" />,
  HTML: <SiHtml5 size={ICON_SIZE} color="#F06525" />,
  JavaScript: <SiJavascript size={ICON_SIZE} color="#FDDC01" />,
  Jest: <SiJest size={ICON_SIZE} color="#15C312" />,
  Laravel: <SiLaravel size={ICON_SIZE} color="#FB503B" />,
  PostgreSql: <BiLogoPostgresql size={ICON_SIZE} color="#336690" />,
  Prisma: <SiPrisma size={ICON_SIZE} color="#2C3648" />,
  Redis: <SiRedis size={ICON_SIZE} color="#D82C20" />,
  Redux: <SiRedux size={ICON_SIZE} color="#764BBD" />,
  SASS: <SiSass size={ICON_SIZE} color="#CE649B" />,
  TailwindCSS: <SiTailwindcss size={ICON_SIZE} color="#38BDF8" />,
  TypeScript: <SiTypescript size={ICON_SIZE} color="#3078C7" />,
  Vite: <SiVite size={ICON_SIZE} color="#689EFE" />,
};
